import os
import file_reader

script_directory = os.path.dirname(os.path.abspath(__file__))
file_path = os.path.join(script_directory, file_reader.filename)

with open(file_path) as f:
    content = f.readlines()

    # line iterator
    total = 0
    line_index = 0
    while line_index < len(content):
        numbers = content[line_index].split(":")[1].split("|")

        winning_numbers = numbers[0].strip().split(" ")
        eligible_numbers = numbers[1].strip().split(" ")

        card_score = 0
        first_winner = True
        for number in eligible_numbers:
            # skip extra spaces generated by single digits
            if number == '':
                continue
            if number in winning_numbers:
                if first_winner:
                    card_score = 1
                    first_winner = False
                else:
                    card_score *= 2
        
        total += card_score

        line_index += 1

        print("Card number, score, total:", line_index, card_score, total)