import os
import file_reader

script_directory = os.path.dirname(os.path.abspath(__file__))
file_path = os.path.join(script_directory, file_reader.filename)

with open(file_path) as f:
    content = f.readlines()
    # generate a map where the card number is each index
    card_map = {}

    # line iterator
    total = 0
    line_index = 0
    while line_index < len(content):
        card_number = line_index + 1

        if card_number not in card_map:
            card_map[card_number] = 1

        numbers = content[line_index].split(":")[1].split("|")

        winning_numbers = numbers[0].strip().split(" ")
        eligible_numbers = numbers[1].strip().split(" ")

        num_winners = 0
        for number in eligible_numbers:
            # skip extra spaces generated by single digits
            if number == '':
                continue
            if number in winning_numbers:
                num_winners += 1
        
        copies = card_map[card_number]
        # run through the next num_winners values in the card_map
        i = card_number + 1
        while i <= card_number + num_winners:
            if i not in card_map:
                card_map[i] = 1 + copies
            else:
                card_map[i] += copies
            i += 1
        
        total += copies

        line_index += 1
        
    print(card_map)
    print(total)